version: "3"
services:
  webhook:
    image: webhook
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SIGNATURE_SECRET: ${SIGNATURE_SECRET}
    ports:
      - 9000:80
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:
