version: "3"
services:
  api:
    build: .
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SIGNATURE_SECRET: ${SIGNATURE_SECRET}
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./data:/data

